header:
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
base_url: https://www.funda.nl/en
keep_cols:
  sold_data:
    - date_sold
    - ym_sold
    - year_sold
#    - term_days
  selling_data:
    - url
    - house_id
    - city
    - house_type
    - building_type
    - price
    - price_m2
    - room
    - bedroom
    - bathroom
    - living_area
    - energy_label
    - zip
    - address
    - year_built
    - house_age
    # - date_list
    # - ym_list
    # - year_list
    - descrip
    - photo
css_selector:
  url: none
  price: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div.mb-4.border-b.border-solid.border-neutral-20.pb-4 > div.mt-5.flex.flex-wrap.items-center.gap-3.lg\:mt-6 > div > div > span'
  address: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div.mb-4.border-b.border-solid.border-neutral-20.pb-4 > div.relative.flex.justify-between.pt-2.lg\:pt-4 > h1 > span.block.text-2xl.font-bold.md\:text-3xl.lg\:text-4xl'
  descrip: '#headlessui-disclosure-panel-na95v21Wgfm-36'
  listed_since: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(2) > dl > div:nth-child(3) > dd > span'
  zip_code: '.object-header__subtitle'
  size: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(4) > dl > div:nth-child(2) > dd > span'
  year: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(3) > dl > div:nth-child(3) > dd > span'
  living_area: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(4) > dl > div:nth-child(1) > dd > dl > div:nth-child(1) > dd'
  kind_of_house: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(3) > dl > div:nth-child(1) > dd > span'
  building_type: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(3) > dl > div:nth-child(2) > dd > span'
  num_of_rooms: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(5) > dl > div:nth-child(1) > dd > span'
  num_of_bathrooms: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(5) > dl > div:nth-child(2) > dd > span'
  layout: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(5) > dl > div:nth-child(4) > dd > span'
  energy_label: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(6) > dl > div:nth-child(1) > dd > div > div > span'
  insulation: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(6) > dl > div:nth-child(2) > dd > span'
  heating: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(6) > dl > div:nth-child(3) > dd > span'
  ownership: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(7) > dl > div > dd > dl > div:nth-child(2) > dd'
  exteriors: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(8) > dl > div:nth-child(1) > dd > span'
  neighborhood_name: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div.mb-4.border-b.border-solid.border-neutral-20.pb-4 > div.relative.flex.justify-between.pt-2.lg\:pt-4 > h1 > a'
  last_ask_price: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(2) > dl > div:nth-child(1) > dd > span'
  last_ask_price_m2: '#__nuxt > section > main > div > div.relative.m-auto.flex.max-w-screen-lg.flex-col.lg\:flex-row.xl\:px-0 > div.mt-4.px-4.lg\:mt-6.lg\:w-\[70\%\].lg\:pr-6 > div:nth-child(2) > section.mt-6.md\:mt-7 > div:nth-child(2) > dl > div:nth-child(2) > dd > span'
  photo: '.media-viewer-overview__section-list-item--photo img[data-lazy]'
